# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:

    profile.validator_constraint.email_should_be_unique:
        class: ProfileBundle\Validation\Constraints\EmailShouldBeUniqueValidator
        arguments:
            - "@profile.repository.account"
        tags:
            - { name: validator.constraint_validator }

    profile.repository.account:
        class: ProfileBundle\Entity\AccountRepository
        factory: [ "@doctrine", getRepository ]
        arguments: [ ProfileBundle\Entity\Account ]
